import type { Metadata } from "next";
import "../globals.css";
import ButtonSignIn from "../components/buttonSignIn";
export const metadata: Metadata = {
  title: "FrameBook",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-[#233931] h-15 flex justify-between items-center px-4">
            <div className="w-full flex justify-between items-center">
              <p className="text-white text-lg font-semibold">FrameBook</p>
              <ButtonSignIn title="Sign In" />
            </div>
        </header>
        {children}
      </body>
    </html>
  );
}
