import type { Metadata } from "next";
import "../globals.css";
import Button from "@/app/components/button";
import Sidebar from "@/app/components/sidebar";
import Link from "next/link";
export const metadata: Metadata = {
  title: "FrameBook",
  description: "Generated by create next app",
};

export default function HomepageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-full bg-[#bcc1c0] grid grid-cols-8 gap-2">
          <div className="col-span-8">
            <header className="bg-[#233931] h-15 flex justify-between items-center px-4 py-2">
              <Link href="/home-page">
                <p className="text-white text-lg font-semibold">FrameBook</p>
              </Link>
              <Button title="Sign In" />
            </header>
          </div>
          <div className="col-span-2">
            <Sidebar />
          </div>
          <main className="col-span-6 p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
